services:
  ai-service:
    build:
      context: ./services
      dockerfile: Dockerfile

    container_name: mentrix-ai
    restart: unless-stopped

    env_file:
      - ./services/.env

    ports:
      - "8000:8000"

    volumes:
      - ./services/uploads:/app/uploads

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      minio:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  minio_data:
